services:
  - type: web
    name: gym-management-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://gym-management-backend.onrender.com/api
    healthCheckPath: /
    autoDeploy: true
