services:
  - type: web
    name: gym-management-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: BCRYPT_ROUNDS
        value: 12
    healthCheckPath: /api/health
    autoDeploy: true
